version: '3.8'

services:
  postgres:
    ports:
      - "5432:5432"
    image: postgres:latest
   
    environment:
      - POSTGRES_USER = docker
      - POSTGRES_PASSWORD = docker
      - POSTGRES_DB = shortlinks
   

  redis:
    image: redis:latest

    ports:
      - "6379:6379"

    environment:
      - REDIS_PASSWORD = docker

   

   