POST http://localhost:3333/api/links
Content-Type: application/json

{
  "code": "teste8",
  "url": "https://google.com"
}

###

GET http://localhost:3333/api/links

###

GET http://localhost:3333/api/metrics

###

GET http://localhost:3333/teste8

